name: Android CI Workflow

on:
  push:
    branches:
      - main
    tags:
      - 'v1.*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Run Tests
        run: bash ./gradlew test --stacktrace
  apk:
    name: Generate APK
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Build APK
        run: bash ./gradlew assembleRelease --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-release.apk
  release:
    name: Release APK
    needs: apk
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Download APK from build
        uses: actions/download-artifact@v3
        id: download
        with:
          name: apk
          path: ~/download/
      - name: Display structure of downloaded files
        run: ls -R ~/download/
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ~/download/app-release.apk
          artifactContentType: application/zip
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload To Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ SERVICE_ACCOUNT_JSON }}
          packageName: io.github.iplanetcn.app.stopwatch
          releaseFile: ~/download/app-release.apk
          track: production
          inAppUpdatePriority: 2
          userFraction: 0.33
          whatsNewDirectory: distribution/whatsnew
          mappingFile: app/build/outputs/mapping/release/mapping.txt